version: "3"

tasks:
  default:
    cmds:
    - task: build
    - task: package

  act:pullrequest:
    cmds:
    - act pull_request -j 'act-test' -e act/pull-request.json --secret-file act/local.secrets --use-gitignore=false

  act:push:
    cmds:
    - act push -j 'act-test' -e act/push.json --secret-file act/local.secrets --use-gitignore=false

  all:
    cmds:
    - task: init
    - task: build
    - task: format
    - task: lint
    - task: package
    - task: test

  init:
    cmds:
    - npm install

  build:
    cmds:
    - npm run build

  format:
    cmds:
    - npm run format

  format-check:
    cmds:
    - npm run format-check

  lint:
    cmds:
    - npm run lint

  package:
    cmds:
    - npm run package

  test:
    cmds:
    - npm run test
