name: release

on:
  release:
    types:
    - "published"

jobs:
  release:
    name: release
    runs-on: ubuntu-latest

    steps:
    - name: checkout repository
      uses: actions/checkout@v4
      # with:
      #   # use PAT because main branch is a protected branch
      #   token: ${{ secrets.PAT }}

    - uses: google-github-actions/release-please-action@v3
      with:
        extra-files: |
          README.md
        release-type: node
        prerelease: true # to create orphan later
        pull-request-title-pattern: "chore(release): ${component} ${version}"
        changelog-types: >
          [
            { "type": "feat", "section": "Features" },
            { "type": "fix", "section": "Bug Fixes" },
            { "type": "revert", "section": "Reverts" },
            { "type": "chore", "section": "Miscellaneous Chores" },
            { "type": "docs", "section": "Documentation" },
            { "type": "test", "section": "Tests", "hidden": "true" },
            { "type": "ci", "section": "Continuous Integration", "hidden": "true" }
          ]
